### ISSUE TITLE
Bug: Setting an audio device id in Source option crashes rainmeter. 

### ISSUE THREAD

**Issue by LI7XI** [d-uzlov/Rainmeter-Plugins-by-rxtd#10]
Hey!

In parent measure, if you set `Source` option to some audio device id rainmeter will crash.

Here is the skin, the id is optained using section variables:

```ini
[MeasureAudio]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Parent
MagicNumber=104
Source=ID: {0.0.0.00000000}.{c73b9bf1-9f30-4a46-9786-c5d3d2c18aba}
```

**Comment by d-uzlov** [comment]
Oh, again. There was this same issue long time ago, and I thought I fixed it.
Thank you for your report, I will look into it.

**Comment by d-uzlov** [comment]
Oh, interesting, I didn't know Github automatically closes the issue with certain commit messages.
Well, I guess you can reopen it if device selection by ID doesn't work in next version.
