### ISSUE TITLE
Bug: setting Gain parameter in custom filters to a floating point leads to a crash.

### ISSUE THREAD

**Issue by LI7XI** [d-uzlov/Rainmeter-Plugins-by-rxtd#12]
Hello, i was messing around with filters then i used `bqPeak(Q 0.5, Freq 100, Gain 5)` custom filter, i tried lowering gain to less than 1 (even though i know its range is [1, 5]), but when i used 0.3, rainmeter crashed.

Idk which one caused the crash, using float point or using a value that is less than 1.

**Comment by d-uzlov** [comment]
I can't replicate this.
Can you check if it was caused by something else?
If the crash is consistent for you, please, post full skin here.

Also, gain can have any value. In the v2.0 only `order` option in Butterworth filters is limited to range [1, 5].

**Comment by LI7XI** [comment]
Hmm.. maybe i was mistaken, i can't replicate anymore.
If it happened again i'll reopen this issue 👍
