### ISSUE TITLE
"Plugin: Unable to load" error on some devices

### ISSUE THREAD

**Issue by sctanf** [d-uzlov/Rainmeter-Plugins-by-rxtd#13]
On my laptop, all the child measures give a "Plugin: Unable to load" error and I cannot figure out why. On my desktop, the plugin loads normally.

**Comment by d-uzlov** [comment]
So, parent measure loads without issues?
If yes, then check if you specified plugin name correctly in the child measures.
The difference between desktop and laptop may be caused by the fact that on desktop you have another plugin (well, previous version of this plugin with different name), and on laptop you don't have it.

**Comment by sctanf** [comment]
That is correct. However, AudioAnalyzer says it's version 2.0.3.3, should be the same installed on both computers, and the skin used is identical.

**Comment by d-uzlov** [comment]
Could you post the skin here?

**Comment by sctanf** [comment]
I have it on a repository here: https://github.com/sctanf/vectorcopy2

**Comment by d-uzlov** [comment]
Well, you see, "Plugin: Unable to load" message comes from the rainmeter when, you guessed it, it asked system to load a file and loading failed. Like, file doesn't exist, or file is not a valid .dll file.
If used 2 times in a row with the same file, second loading it does nothing. Plugin is already loaded, there is nothing to do, so nothing can go wrong.
So a situation when parent measure has successfully loaded but child measures did not, _I believe_ is technically not possible. Even if something has moved/renamed plugin file between loads, it will be loaded from cache.

If you believe that generated files on your laptop are correct, then the only hypothesis I have is that code that loads the plugin the first time doesn't actually load it successfully, and Rainmeter somehow doesn't catch it and so there is no message in logs, but on second load and later Rainmeter understands that an error happened and write a message into logs.

How do you know that parent measure has successfully loaded?
You can quickly check if it actually works using section variables or `callback-onDeviceChange` option.

Also, if plugin doesn't load at all on some machine, the first thing that comes to mind is that some of the VC runtime files are missing. Check if you laptop has the latest VC runtime installed.

**Comment by sctanf** [comment]
I tested using the callback, didn't work, so the plugin never actually loaded. Installing the latest VC runtime did the trick, callback worked, and plugin loads properly, thanks @d-uzlov
