### ISSUE TITLE
Bug: Map transofmation doesn't work as expected.

### ISSUE THREAD

**Issue by LI7XI** [d-uzlov/Rainmeter-Plugins-by-rxtd#5]
Here is the skin, using the newest alpha release:

<details>

```ini
[Rainmeter]
Update=[#UpdateRate]

[Variables]
Fps=30
UpdateRate=(1000 / #Fps#)

[MeasureAudio]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Parent
MagicNumber=104
ProcessingUnits=Main
Unit-Main=Channels Auto | Handlers LoudnessdB, LoudnessPerecnt(LoudnessdB) | Filter like-a
Handler-LoudnessdB=Type Loudness | Transform dB
Handler-LoudnessPerecnt=Type ValueTransformer | Transform Map(From -50 : 0)

[MeasureLoudnessdB]
Measure=plugin
Plugin=AudioAnalyzer
Type=Child
Parent=MeasureAudio
Channel=auto
ValueId=LoudnessdB

[MeasureLoudness]
Measure=plugin
Plugin=AudioAnalyzer
Type=Child
Parent=MeasureAudio
Channel=auto
ValueId=LoudnessPerecnt

[MeterString]
Meter=String
```

</details>

First case: Using `Map(From -50 : 0)` without the `to` argument or `Clamp` parameter.

What i expected: Since `to` argument is not required, and the plugin will use the default [0, 1] range, i expect it to work more like `Clamp`.

What i got: Values go out of range when there is silence then sound.

![image](https://user-images.githubusercontent.com/55055075/110699553-a7f9c000-81f7-11eb-9a93-db661dd8343c.png)

---

Second case: Using `Map(From -50 : 0, to 5 : 50)` without the `Clamp` parameter.

What i expected: Output value and measure range should be [5, 50].

What i got: (even when there is sound playing).

![image](https://user-images.githubusercontent.com/55055075/110702507-46d3eb80-81fb-11eb-87fc-c110830d45f6.png)

---

Third case: Using `Map(From -50 : 0, to 5 : 50), Clamp(Min 5 ,Max 50)`.

What i expected: Output value and measure range **must** be [5, 50].

What i got:

![image](https://user-images.githubusercontent.com/55055075/110702913-cfeb2280-81fb-11eb-9641-2c721d14ed1e.png)

---

This issue is not just in Loudness handler, it's in the transformers themselves.
I get same results even when trying different handlers: `RMS`, `Peak`, `FFT`.

**Comment by d-uzlov** [comment]
> What i expected: Since `to` argument is not required, and the plugin will use the default [0, 1] range, i expect it to work more like `Clamp`.

> Second case: Using `Map(From -50 : 0, to 5 : 50)` without the `Clamp` parameter.
> What i expected: Output value and measure range should be [5, 50].

`Map` doesn't work this way. Map doesn't imply clamp.
When you write `Map(From -50 : 0, to 5 : 50)`, then values inside range `-50 : 0` get transformed into range `5 : 50`, but values outside `-50 : 0` range after transformation also end up outside of desired output range, with the same linear interpolation parameters.
For example, if you write `map(from 0:1, to 0:2)`, then all values will be multiplied by 2, regardless if they fall into source range.
So if you want to limit values to some range, then you have to explicitly specify `clamp` transform.

> Third case: Using `Map(From -50 : 0, to 5 : 50), Clamp(Min 5 ,Max 50)`.
> 
> What i expected: Output value and measure range **must** be [5, 50].

From what I understand, your concern is that Rainmeter shows measure range as [0.0, 5.0].
This is Rainmeter thing. If you don't specify min-max values explicitly in measure options, then by default it sets that measure range is [0.0, 1.0], and then adjusts the range low bound to lowest values from a measure, and range high bound to measure max value.
However, if a measure always produces values more than 0 (more than 5 in your case), then Rainmeter doesn't adjust min values automatically: it always stays at 0.
Same goes for measures that always produce values below 1.0: Rainmeter keeps their max value in statistics at 1.0.

**Comment by LI7XI** [comment]
>So if you want to limit values to some range, then you have to explicitly specify clamp transform.

Oh, i got it now.

>From what I understand, your concern is that Rainmeter shows measure range as [0.0, 5.0].

Nope, actually the measure is literally stuck at [0, 5] range, in case of using `Map(From -50 : 0, to 5 : 50), Clamp(Min 5 ,Max 50)` the measure always gives 5 as a value.

>However, if a measure always produces values more than 0 (more than 5 in your case), then Rainmeter doesn't adjust min values automatically: it always stays at 0.
Same goes for measures that always produce values below 1.0: Rainmeter keeps their max value in statistics at 1.0.

I know but the measure doesn't provide value in [5, 50] range at all, the maximum output is always 5.

**Comment by d-uzlov** [comment]
> Nope, actually the measure is literally stuck at [0, 5] range, in case of using `Map(From -50 : 0, to 5 : 50), Clamp(Min 5 ,Max 50)` the measure always gives 5 as a value.

I can't reproduce this on current dev version. I have changed some of the related code, maybe this bug has already been fixed.
I will post new binaries today (or maybe tomorrow).

**Comment by d-uzlov** [comment]
I published alpha3 release.
Please, test it the issue occurs on this version.

**Comment by LI7XI** [comment]
>In case of using Map(From -50 : 0, to 5 : 50), Clamp(Min 5 ,Max 50) the measure always gives 5 as a value.
>Please, test it the issue occurs on this version.

It works perfectly as expected, Thanks ^^
