### ISSUE TITLE
UpdateInterval parameter is not available.

### ISSUE THREAD

**Issue by LI7XI** [d-uzlov/Rainmeter-Plugins-by-rxtd#6]
When using `UpdateInterval` parameter in `RMS` or `Peak` handler it gives an error message about unused option.

>Main: Peak: unused options: '[UpdateInterval]' (AudioAnalyzerExamples\Peak\AudioAnalyzer.ini - [MeasureAudio])

Here is the skin:

<details>

```ini
[Rainmeter]
Update=[#UpdateRate]

[Variables]
Fps=30
UpdateRate=(1000 / #Fps#)

[MeasureAudio]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Parent
MagicNumber=104
ProcessingUnits=Main
Unit-Main=Channels Left, Right | Handlers Peak | Filter none
Handler-Peak=Type Peak | Transform db, Map(From -50 : 0), Clamp | UpdateInterval 5 | Attack 20 | Decay 40

[MeasurePeakL]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Channel=Left
ValueId=Peak

[MeasurePeakR]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Channel=Right
ValueId=Peak

[MeterString]
Meter=String
```

</details>

**Comment by d-uzlov** [comment]
`UpdateInterval` is an old option, that was removed long time ago, right after 1.1.5 release, IIRC.
New option is `UpdateRate`, which specifies number of updates per second. It is used both in RMS and Peak handlers.
I updated the documentation along with the option change, but maybe I pushed the commit after some delay and you probably got outdated documentation before the repo on github was updated.
